### PR TITLE
fix for dropped columns breaking incr fetch

### LINKED ISSUE #67: Incremental fetching not working correctly in some cases
The Last fetched value is not correctly shown/saved while incremental load is used.

Snímek z 2019-06-06 13-07-39
^^^ the incremental column is `updated_at` which is a timestamp, but Last Fetched Value is get from another column. In this case is get from column "slug" which is next in the column order. 

I look to source code and I think it will destroy incremental fetching logic. 

Client try to reset state file but it won't help.

More info in ticket https://keboola.zendesk.com/agent/tickets/10675 and in extractor https://connection.keboola.com/admin/projects/6296/extractors/keboola.ex-db-pgsql/509902630/query/34887

### PR DESCRIPTION
**Pull request by pivnicek**
fixes #67 

so far just the test is here.

### CODE REVIEW

**Comment by pivnicek** [comment]
Sorry @tomasfejfar , but the code you pointed to is handling user selected columns, but this issue is independent of whether the user selects columns or not.

**Comment by tomasfejfar** [comment]
I see, so the test is incorrect or incomplete then. Because it passes with my fix and without your fix.

**Comment by tomasfejfar** [comment]
Oh I see... it comes from here https://github.com/keboola/db-extractor-pgsql/blob/754dfd8558fb0d95a1b6703215e641cd9497e743/src/Keboola/DbExtractor/Extractor/PgSQL.php#L526

**Comment by tomasfejfar** [comment]
I further updated my update then - to fix the very underlying issue - that the columns array is indexed by staggered indexes. 

Thanks for the catch 👍

**Comment by pivnicek** [comment]
ok @tomasfejfar your (new) way is fine by me, but we'll need to update the getTables test to reflect the indices change, I'll do that now.

**Comment by tomasfejfar** [comment]
Huh, that's actually weird - shouldn't the keys be ksorted? In the test they are 2 - 0 - 3...

https://github.com/keboola/db-extractor-pgsql/blob/57119ea9f8265baaa2cd1e03cf2bd0e707469026/tests/Keboola/Extractor/PgsqlTest.php#L176-L208

**Comment by pivnicek** [comment]
yes, they should imho, it is weird.

**Comment by pivnicek** [comment]
ok @tomasfejfar I put your array_values addition at the end of the getTables (so it does it only once all the data is there) and it seems to be working as expected now.

File: tests/Keboola/Extractor/PgsqlTest.php [hunk 1]
```diff
@@ -162,6 +162,17 @@ public function testGetTables(): void
                     'type' => 'table',
                     'columns' =>
                         array (
+                            0 =>
```
Comment (tomasfejfar) [inline tests/Keboola/Extractor/PgsqlTest.php]: That's not a proper fix IMHO... it passes, so it does not test it properly... we need to make it fail first for this data set and then fix the dataset when we're sure it's already testing the structure.

Comment (tomasfejfar) [reply tests/Keboola/Extractor/PgsqlTest.php]: But let's fix this in https://github.com/keboola/db-extractor-pgsql/issues/70

Comment (pivnicek) [reply tests/Keboola/Extractor/PgsqlTest.php]: huh? that's what I did.  I changed the expected output to what we want, this, and then fixed the source so that it produced the expected output

Comment (tomasfejfar) [reply tests/Keboola/Extractor/PgsqlTest.php]: Have you seen it fail? ;) 

image

Comment (pivnicek) [reply tests/Keboola/Extractor/PgsqlTest.php]: yes, without ecd05bd it fails.

Comment (tomasfejfar) [reply tests/Keboola/Extractor/PgsqlTest.php]: Huh, not for me. Unless there is [assertSame here](https://github.com/keboola/db-extractor-pgsql/blob/7a95dfe9b90d6dae3bdde38189919d47fbef2c4d/tests/Keboola/Extractor/PgsqlTest.php#L297) it won't fail in any case

Comment (tomasfejfar) [reply tests/Keboola/Extractor/PgsqlTest.php]: I mean the order. You fixed the test that the columns are not in natural order 0 1 2 3. But have you seen it fail with 0 2 1 3? I don't think you did. Because assertEquals just checks if the structure can be found inside, not that it's exactly the same. 

```
assertEquals([0=>'a', 1=>'b'], [1=>'b', 0=>'a']) // OK
assertSame([0=>'a', 1=>'b'], [1=>'b', 0=>'a']) // ERROR
```
