### PR TITLE
Use forceFallback to test incremental fetching state bug

### LINKED ISSUE #56: Dropping lastFetchedValue
I seems that it can happen when the \copy command fails and it uses PDO it may drop the `lastFetchedValue`

### PR DESCRIPTION
**Pull request by pivnicek**
fixes #56

### CODE REVIEW

File: tests/Keboola/Extractor/IncrementalFetchingTest.php [hunk 1]
```diff
@@ -359,6 +359,45 @@ public function testIncrementalOrdering(): void
         }
     }
 
+    public function testIncrementalFetchingPDOFallback(): void
+    {
+        $this->createAutoIncrementAndTimestampTable();
+        $config = $this->getIncrementalFetchingConfig();
+
+        $result = ($this->createApplication($config))->run();
```
Comment (tomasfejfar) [inline tests/Keboola/Extractor/IncrementalFetchingTest.php]: you could supply custom logger that would haev TestHandler and actually test that it forced the fallback. Currently you only test that the parameter's existence does not break it. Not that it actually does anything.

Comment (pivnicek) [reply tests/Keboola/Extractor/IncrementalFetchingTest.php]: good idea.  It does do something!

Comment (tomasfejfar) [reply tests/Keboola/Extractor/IncrementalFetchingTest.php]: Not that I don't believe you 😁 Just the test does not reflect that 😋

File: tests/Keboola/Extractor/IncrementalFetchingTest.php [hunk 2]
```diff
@@ -359,6 +361,50 @@ public function testIncrementalOrdering(): void
...
+        ]);
+        // set the config to use the pdo fallback
+        $config['parameters']['forceFallback'] = true;
+        // use a test logger to make sure we can tell that it actually falls back to pdo
+        $handler = new TestHandler();
+        $logger = new Logger('test');
+        $logger->pushHandler($handler);
+        $newResult = ($this->createApplication($config, $result['state'], $logger))->run();
+
+        $this->assertTrue($handler->hasInfoThatContains("Executing query via PDO"));
```
Comment (tomasfejfar) [inline tests/Keboola/Extractor/IncrementalFetchingTest.php]: Could you pls make it a check for all expected values? I think this might output `"Unexpected exception executing \copy: "` as well! That's certainly not what we want.

Comment (tomasfejfar) [reply tests/Keboola/Extractor/IncrementalFetchingTest.php]: Just as I expected `Unexpected exception executing \copy: Forcing extractor to use PDO fallback fetching` :(
